# numpy 복습

In [3]:
import numpy as np

In [4]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [5]:
data2 = [0.1,5,4,12,0.5]
a2 = np.array(data2) #모두 float으로 저장됨
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [6]:
print(a1.dtype) #dtype함수는 배열의 데이터타입알아보기
print(a2.dtype)

int32
float64


In [8]:
np.arange(0,10,2) #start stop 몇번띄어넘는지 가능

array([0, 2, 4, 6, 8])

In [9]:
np.arange(12).reshape(4,3) #12까지 배열만든뒤에 reshape로 행렬만들기

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
np.linspace(0,np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [12]:
np.zeros(10) #only 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(10) #only 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.eye(3) #단위행렬만들기

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
str_a1 = np.array(['1.567','0.123','5.123','9','8'])
num_a1 = str_a1.astype(float) #astype으로 데이터타입바꾸기
num_a1.dtype

dtype('float64')

In [23]:
str_a2 = np.array(['1','2','3','4','5'])
num_a2 = str_a2.astype(int)

In [24]:
print(str_a2.dtype)
print(num_a2.dtype)

<U1
int32


In [27]:
np.random.rand(2,3) #실수난수
np.random.randint(2,10,4) #정수난수

array([8, 4, 6, 8])

In [28]:
np.random.randint(10,size=(3,4)) #지정범위 정수난수 배열 생성

array([[1, 8, 3, 9],
       [5, 8, 0, 0],
       [6, 9, 7, 7]])

In [29]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [30]:
arr1+arr2 #사칙연산 다됨

array([11, 22, 33, 44])

In [36]:
arr3 = np.arange(5)
[arr3.sum(),arr3.mean()] #합 평균 구하기

[10, 2.0]

In [38]:
[arr3.std(),arr3.var()] #표편, 분산 구하기

[1.4142135623730951, 2.0]

In [39]:
[arr3.min(),arr3.max()] #최소, 최대값

[0, 4]

In [42]:
arr4 = np.arange(1,5)
arr4.cumsum() #누적합

array([ 1,  3,  6, 10], dtype=int32)

In [43]:
arr4.cumprod() #누적곱

array([ 1,  2,  6, 24], dtype=int32)

In [44]:
A = np.array([0,1,2,3]).reshape(2,2)
B = np.array([3,2,0,1]).reshape(2,2)

In [46]:
np.dot(A,B) #행렬곱

array([[0, 1],
       [6, 7]])

In [47]:
np.transpose(A) #전치행렬

array([[0, 2],
       [1, 3]])

In [48]:
[np.linalg.inv(A), np.linalg.det(A)] #역행렬, 행렬식 구하기

[array([[-1.5,  0.5],
        [ 1. ,  0. ]]),
 -2.0]

#### 배열의 인덱싱

In [49]:
a1 = np.array([0,10,20,30,40,50])
a1[0]

0

In [51]:
a1[5] = 70 #변경도 가능
a1

array([ 0, 10, 20, 30, 40, 70])

In [52]:
a1[[1,2,3]]

array([10, 20, 30])

In [55]:
a2 = np.arange(10,100,10).reshape(3,3)
a2[0,2] #[행,열]

30

In [58]:
a2[2,2] = 95 #값 변경가능
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [57]:
a2[1,] # 행전체가져오기 

array([40, 50, 60])

In [59]:
a2[1,] = np.array([45,55,65]) #행전체도 변경가능
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [60]:
a2[[0,2],[0,1]] #앞에거부터 0,0 2,1을 불러옴

array([10, 80])

In [61]:
a = np.array([1,2,3,4,5,6])
a[a>3] #조건을 넣어도됨

array([4, 5, 6])

#### 배열의 슬라이싱 

In [62]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [63]:
b1[2:5] = np.array([25,35,45]) #변경도 가능
b1

array([ 0, 10, 25, 35, 45, 50])

In [64]:
b1[3:6] = 60 #싹다 바꿈
b1

array([ 0, 10, 25, 60, 60, 60])

In [67]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [66]:
b2[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [68]:
b2[:3,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])